config/routes.rb
SnellMail::Application.routes.draw do

  root to: 'sessions#new'

  match "/users/change_password" => "users#password",
    as: :change_password

  match "cohabitants/:id/toggle_activated" => "cohabitants#toggle_activated",
    as: :toggle_activated

  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:index, :show, :new, :create]
  resources :users
  resources :cohabitants

  match '/signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :admin,
                  :wants_update
  attr_readonly   :notifications

  has_secure_password

  validates :name,     format: { with: Validators.name }
  validates :email,    format: { with: Validators.email }
  validates :password, length: { minimum: 7 }, allow_nil: true

  has_many :notifications
 
  class << self  
    def want_update
      where(wants_update: true)
    end

    def others_that_want_update_emails(notifier)
      where("wants_update = ? AND NOT id = ?", true, notifier.id).map(&:email) 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_admin, only: [:password, :update]
  before_filter :set_user, except: [:index, :new, :create, :password]

  def password
    @user = current_user
    session[:redirect_back] = request.referer
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path,
        flash: { "alert_success" => "#{@user.name} created" }
    else
      render 'new'
    end
  end

  def update
    if changing_password?
      change_password
    elsif @user.update_attributes(params[:user])
      redirect_to users_path, notice: "#{@user.name} updated"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def show
    notifications = @user.notifications
    if notifications.empty?
      @notifications = []
    else
      @notifications = notifications.order('id DESC').page(params[:page]).
                         per_page(RECORDS_PER_PAGE)
    end
  end

  def edit
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def changing_password?
      @old_password = params[:user][:old_password]
    end

    def change_password
      params[:user].delete(:old_password)
      if old_password_authenticates?
        if new_password_confirmed?
          success
        else
          password_confirmation_mismatch
        end
      else
        old_password_mismatch
      end
    end

    def old_password_authenticates?
      @user.authenticate(@old_password)
    end

    def new_password_confirmed?
      @user.update_attributes(params[:user])
    end

    def success
      redirect_from_password_change_success
      session[:redirect_back] = nil
    end

    def password_confirmation_mismatch
      flash[:notice] = "Password confirmation doesn't match"
      redirect_to request.referer
    end

    def old_password_mismatch
      flash[:notice] = "Old password didn't match existing one"
      redirect_to request.referer
    end

    def redirect_from_password_change_success
      flash[:notice] = 'new password saved!'
      redirect_to session[:redirect_back]
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_email(user, current_user_id)
    unless current_user_id == user.id
      mail_to_user_email(user)
    else
      user.email
    end
  end
  
  private
  
    def mail_to_user_email(user)
      mail_to user.email
    end
end

app/views/users/change_password.html.erb
<p><%= @user.name %>, be careful. You're about to change your password.</p>

<%= form_for @user do |f| %>
  <%= f.label :old_password %>
  <%= f.password_field :old_password %>

  <%= f.label :password, 'New password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'New password again' %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Change password' %> 
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/sub_header', klass: 'user', error: false %>
<p class="lead">Edit <%= @user.name %></p>
<%= form_for @user, html: { class: 'form-horizontal span3' } do |f| %>
  <%= f.text_field :email, placeholder: 'Email' %>
  <br>
  <label for="user_admin">
    Admin
    <%= f.check_box :admin %>
  </label>
  <div class="wants-update" style="display:none">
    <label for="user_wants_update">
      Wants update
      <%= f.check_box :wants_update %>
    </label>
  </div>
  <br>
  <%= f.submit 'Save', class: 'btn btn-warning' %>
<% end %>
<br>
<%= link_to 'Change password', change_password_path if @user == current_user %>

<%= render 'shared/errors', object: @user %>

app/views/users/index.html.erb
<%= render 'shared/sub_header', klass: 'user', error: false %>
<h1>All Users</h1>
<br>
<% @users.each do |user| %>
  <ul class="span3 unstyled">
    <li><h3><%= link_to user.name, user %></h3></li>
    <li>
    <%= user_email(user, current_user.id) %>
    </li>
    <br>
    <li><%= button_to "edit", edit_user_path(user), title: "Edit #{user.name}", method: :get, class: "btn btn-warning" %></li>
    <% unless user.id == current_user.id %>
      <li><%= button_to "delete", user, method: :delete, confirm: "Are you sure?",
                title: "Delete #{user.name}", class: "btn btn-danger" %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/sub_header', klass: 'user', error: @user.errors.any? %>
<h1>New user</h1>
<br>
<%= form_for @user, html: { class: 'form-horizontal span3' } do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br><br>
  <%= f.text_field :email, placeholder: "Email" %>
  <br><br>
  <%= f.password_field :password, placeholder: "Password" %>
  <br><br>
  <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
  <br>
  <label for="user_admin">
    Admin
    <%= f.check_box :admin %>
  </label>
  <div class="wants-update" style="display:none">
    <label for="user_wants_update">
      Wants update
      <%= f.check_box :wants_update %>
    </label>
  </div>
  <br>
  <%= f.submit 'Create', class: 'btn btn-success' %>
<% end %>

<%= render 'shared/errors', object: @user %>

app/views/users/password.html.erb
<p class="lead"><%= @user.name %>, be careful. You're about to change your password.</p>

<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <%= f.label :old_password %>
  <%= f.password_field :old_password %>

  <%= f.label :password, 'New password' %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'New password again' %>
  <%= f.password_field :password_confirmation %>

  <br><br>
  <%= f.submit 'Change password', class: 'btn btn-warning' %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/sub_header', klass: 'user', error: false %>
<div class="hero-unit">
  <h1><%= @user.name %></h1>
  <p><%= mail_to @user.email %></p>
</div>
<p class="lead">Notifications</h3>
<% if @notifications.empty? %>
  <p><%= @user.name %> has made no notifications.</p>
<% else %>
<ul>
  <% @notifications.each do |n| %>
    <li><%= link_to n.created_at.strftime('%m.%d.%Y (%A) at %I:%M%P'), n %></li>
  <% end %>
</ul>
  <%= will_paginate @notifications, :class => 'pager' %>
<% end %>