config/routes.rb
SnellMail::Application.routes.draw do

  root to: 'sessions#new'

  match "/users/change_password" => "users#password",
    as: :change_password

  match "cohabitants/:id/toggle_activated" => "cohabitants#toggle_activated",
    as: :toggle_activated

  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:index, :show, :new, :create]
  resources :users
  resources :cohabitants

  match '/signout', to: 'sessions#destroy'

end

app/models/cohabitant.rb
class Cohabitant < ActiveRecord::Base
  validates_presence_of :department, :location, :contact_name, :contact_email
  validates :contact_name, format: { with: Validators.name }
  validates :contact_email, format: { with: Validators.email }

  attr_accessible :department, :location, :contact_name, :contact_email,
                  :activated

  has_and_belongs_to_many :notifications

  def toggle_activated!
    self.update_attributes(activated: !self.activated)
  end

  def self.activated
    where(activated: true)
  end
end

app/controllers/cohabitants_controller.rb
class CohabitantsController < ApplicationController
  before_filter :set_cohabitant, except: [:index, :new, :create]

  def index
    @cohabitants = Cohabitant.all
  end

  def new
    @cohabitant = Cohabitant.new
  end

  def create
    @cohabitant = Cohabitant.new(params[:cohabitant])
    if @cohabitant.save
      redirect_to cohabitants_path, notice: 'New cohabitant successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @cohabitant.update_attributes(params[:cohabitant])
      redirect_to cohabitants_path,
        notice: "#{@cohabitant.department} updated."
    else
      render 'edit'
    end
  end

  def toggle_activated
    @cohabitant.toggle_activated!
    cohabitant_state = CohabitantState.new(@cohabitant)
    cohabitant_state_info = cohabitant_state.info

    redirect_to cohabitants_path,
      flash: { "alert-#{cohabitant_state_info[:flash]}" =>
      "#{@cohabitant.department} #{cohabitant_state_info[:adj]}." }
  end

  def destroy
    @cohabitant.destroy
    redirect_to cohabitants_path
  end

  def show
    @notifications = @cohabitant.notifications.order('id DESC').
      page(params[:page]).per_page(RECORDS_PER_PAGE)
  end

  def edit
  end

  private

    def set_cohabitant
      @cohabitant = Cohabitant.find(params[:id])
    end
end

app/helpers/cohabitants_helper.rb
module CohabitantsHelper
  def toggle_activated_button(cohabitant)
    button_info = if cohabitant.activated?
                    activated_info
                  else
                    deactivated_info
                  end

    button_to button_info[:text], toggle_activated_path(cohabitant),
      title: "#{button_info[:text].capitalize} #{cohabitant.department}",
      class: button_info[:html_class]
  end

  private

    def activated_info
      { text: 'deactivate', html_class: 'btn btn-inverse' }
    end
    
    def deactivated_info
      { text: 'activate', html_class: 'btn' }
    end
end

app/views/cohabitants/edit.html.erb
<%= render 'shared/sub_header', klass: 'cohabitant', error: false %>
<h2>Edit <%= @cohabitant.department %></h2>
<br>
<%= form_for @cohabitant, html: { class: 'form-horizontal span3' } do |f| %>
  <%= f.text_field :location, placeholder: 'Location' %>
  <br><br>
  <%= f.text_field :contact_name, placeholder: 'Contact name' %>
  <br><br>
  <%= f.text_field :contact_email, placeholder: 'Contact email' %>
  <br><br>
  <%= f.submit 'Edit', class: 'btn btn-warning' %>
<% end %>

<%= render 'shared/errors', object: @cohabitant %>

app/views/cohabitants/index.html.erb
<%= render 'shared/sub_header', klass: 'cohabitant', error: false %>
<h1>All Cohabitants</h1>
<p class="lead">Deactivate cohabitants to make them unnotifiable.</p>
<% unless @cohabitants.empty? %>
  <% @cohabitants.each do |cohabitant| %>
    <ul class="span3 unstyled">
      <li><%= link_to cohabitant.department, cohabitant %></li>
      <li><%= cohabitant.location %></li>
      <li><%= cohabitant.contact_name %></li>
      <li><%= mail_to cohabitant.contact_email %></li>
      <li><%= button_to 'edit', edit_cohabitant_path(cohabitant), title: "Edit #{cohabitant.department}", method: :get, class: "btn btn-warning" %></li>
      <li>
        <%= toggle_activated_button(cohabitant) %>
      </li>
      <li><%= button_to "delete", cohabitant, method: :delete,
                confirm: "Are you sure? Deleted Cohabitants will not " +
                  "show up in archived notifications.",
                title: "Delete #{cohabitant.department}",
                class: "btn btn-danger" %>
      </li>
    </ul>
  <% end %>
<% else %>
  <h2>You have no cohabitants! Click New cohabitant to make one.</h2>
<% end %>

app/views/cohabitants/new.html.erb
<%= render 'shared/sub_header', klass: 'cohabitant', error: @cohabitant.errors.any? %>
<h1>New Cohabitant</h1>
<br>
<%= form_for @cohabitant, html: { class: 'form-horizontal span3' } do |f| %>
  <%= f.text_field :department, placeholder: 'Department' %>
  <br><br>
  <%= f.text_field :location, placeholder: 'Location' %>
  <br><br>
  <%= f.text_field :contact_name, placeholder: 'Contact name' %>
  <br><br>
  <%= f.text_field :contact_email, placeholder: 'Contact email' %>
  <br><br>
  <%= f.submit 'Create', class: 'btn btn-success' %>
<% end %>
<br>

<%= render 'shared/errors', object: @cohabitant %>

app/views/cohabitants/show.html.erb
<%= render 'shared/sub_header', klass: 'cohabitant', error: false %>
<div class="hero-unit">
  <h1><%= @cohabitant.department %></h1>
  <% unless @cohabitant.activated? %>
    <h2>(deactivated)</h2>
  <% end %>
  <p><%= mail_to @cohabitant.contact_email %></p>
</div>
<p class="lead">Notifications</h3>
<% unless @notifications.empty? %>
  <table class="table table-striped table-bordered">
    <thead id="table-header">
      <tr>
        <td class="span3"><strong>Notified on</strong></td>
        <td class="span3"><strong>Notifier</strong></td>
      </tr>
    </thead>
    <% @notifications.each do |notification| %>
    <tbody>
      <tr>
        <td><%= link_to notification.created_at.strftime('%A, %B %e %Y'), notification %></td>
        <td>
          <%= notifier(notification) %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= will_paginate @notifications, class: 'pager' %>
<% else %>
  <p><%= @cohabitant.department %> has never been notified.</p>
<% end %>