config/routes.rb
SnellMail::Application.routes.draw do

  root to: 'sessions#new'

  match "/users/change_password" => "users#password",
    as: :change_password

  match "cohabitants/:id/toggle_activated" => "cohabitants#toggle_activated",
    as: :toggle_activated

  resources :sessions, only: [:new, :create, :destroy]
  resources :notifications, only: [:index, :show, :new, :create]
  resources :users
  resources :cohabitants

  match '/signout', to: 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand">
        <%= link_to 'Snell Mail', notifications_path if signed_in? %>
        <%= h 'Snell Mail' if !signed_in? %>
      </div>
      <ul class ="nav nav-pills">
        <% if signed_in? %>
          <% if admin? %>
            <li<%= h " class='active'" if request.original_url =~ /users/ %>><%= link_to 'Users', users_path %></li>
            <li<%= h " class='active'" if request.original_url =~ /cohabitants/ %>><%= link_to 'Cohabitants', cohabitants_path %></li>
          <% else %>
            <li<%= h " class='active'" if request.original_url =~ /password/ %>><%= link_to 'Change password', change_password_path %></li>
          <% end %>
          <li<%= h " class='active'" if request.original_url =~ /notifications/ %>><%= link_to 'Notifications', notifications_path %></li>
          <li><%= link_to 'Sign out', signout_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snell Mail</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span6 offset3">
        <%= render 'layouts/header' %>
      </div>
    </div>
    <% if flash.any? %>
    <div class="row">
      <div class="span6 offset3">
        <% flash.each do |key, value| %>
          <div class="alert <%= key %>">
            <a class="close" data-dismiss="alert" href="#">cool</a>
            <p><%= value %></p>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="span6 offset3">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>